### ISSUE TITLE
Other player's backpack title wrong

### ISSUE THREAD

**Issue by alexmartz710** [GeorgH93/Minepacks#101]
### Information
**Environment information**
*Plugin + server version info*:

```

##### Start Minepacks version info ####
Minepacks: 2.3.11-Release
Server: git-Paper-90 (MC: 1.16.1)
Java: 1.8.0_181
#####  End Minepacks version info  #####

```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

https://gist.github.com/alexmartz710/87251909d651e4fa3750319ddf6bd4ce.js

```

### Details
**Description**  
Whenever I open another person's backpack, the title of their backpack is wrong. It does open the right backback however.

**Steps to reproduce**  
/bp open <playername>

**Expected behavior**  
For the title to be the right owner of the backpack instead of some random player online in my server.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
I figure it has something to do with the {OwnerName} tag in the config file not working as it should.

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/215/artifact/a/Minepacks-2.3.12-SNAPSHOT-Release.jar).
