### ISSUE TITLE
Backpack lost on join

### ISSUE THREAD

**Issue by Ant4rez** [GeorgH93/Minepacks#102]
Hi, i think there is an issue with other plugin called "[AdvancedLogin](https://www.spigotmc.org/resources/advancedlogin-pin-gui-login.10510/)".

When you join the server, the backpack automaticly appears on your hotbar, but when you log in the backpack disappears.

---------------------
**Server Info:**
Minepacks: 2.3.11-Release
Server: git-Paper-93 (MC: 1.16.1)
Java: 1.8.0_261

**Comment by GeorgH93** [comment]
I will not fix it. There are too many login plugins available.
The player will receive the backpack once the respawn or switch world.

The next feature update (v3.0) will add a command that the players can use the spawn the item. If your login plugin allows you to run commands after login (as the player) you will be able to use this command as a workaround.

**Comment by Ant4rez** [comment]
Thanks for the answer, anyways i contacted the advancedlogin developer if he can do something for this issue.
