### ISSUE TITLE
backpack open error

### ISSUE THREAD

**Issue by steven11304** [GeorgH93/Minepacks#104]
when i try to open and modify other player's backpack ,i got kicked with packet processing error
![未命名](https://user-images.githubusercontent.com/64590190/88492735-6fe29b80-cfdf-11ea-8e56-19693a0a2f4c.png)

https://paste.gg/p/anonymous/229a0d0354f548f098801a70aace1c8f

**Comment by GeorgH93** [comment]
Please make sure that you are using [v2.3.11](https://github.com/GeorgH93/Minepacks/releases/download/v2.3.11/Minepacks-2.3.11-Release.jar).
If you are already using that version please me with the output of `/marry version` (it gives more than just the plugins version).
