### ISSUE TITLE
My users lost all their belongings

### ISSUE THREAD

**Issue by ToxicPeople** [GeorgH93/Minepacks#111]
My users lost all their belongings, they kept their things in their / backpack to later log out, at the moment they logged in they found the inconvenience that their backpacks were EMPTY. I want to know how to fix this urgently, since it is the progress of 5 months of server. And you can't lose everything in one afternoon due to a plugin malfunction.

**Comment by GeorgH93** [comment]
Some more details would be nice.
What's your server version? And which server software are you using?
Have you changed anything before loosing the backpacks?
Logs??? (Preferable from when the user last used the backpack and when the user joint again)
Which other plugins are you using?
Whats your plugin config?

**Comment by zelotbe** [comment]
Hi!
I'm having the same issue on my server.
When a user relogs everything inside the backpack is gone.
Minecraft Version: 1.16.2
Plugins: EssenstialsX, Luckperms, Angelchest, Jukebox, Harbor, Spark.
However I do get console errors from players.
Example: 
`07.09 19:12:12 [Server] WARN Failed saving backpack for: SeikatsuJojo (Unable to get players ID from database)
07.09 19:12:12 [Server] INFO Backup of the backpack has been created: /plugins/Minepacks/backups/SeikatsuJojo_d5b59010b0084b91953d215f742c6b46_1599505932326.backpack`

**Comment by GeorgH93** [comment]
> 
> 
> Hi!
> I'm having the same issue on my server.
> When a user relogs everything inside the backpack is gone.
> Minecraft Version: 1.16.2
> Plugins: EssenstialsX, Luckperms, Angelchest, Jukebox, Harbor, Spark.
> However I do get console errors from players.
> Example:
> `07.09 19:12:12 [Server] WARN Failed saving backpack for: SeikatsuJojo (Unable to get players ID from database) 07.09 19:12:12 [Server] INFO Backup of the backpack has been created: /plugins/Minepacks/backups/SeikatsuJojo_d5b59010b0084b91953d215f742c6b46_1599505932326.backpack`

Looks like you have some problem with your database. Could you please share your full server log file with me?

**Comment by thecenters** [comment]
I'm having backpacks disappear on my server as well. Searched my log and couldn't find any errors.
