### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by AndreyADeveloper** [GeorgH93/Minepacks#112]
### Help request

**I'm having issues giving other users on my server access to the Backpack**

**So far I've tried going on the Wiki, however, I had not found anything.**

**Comment by GeorgH93** [comment]
Players need the `backpack.use` permission to be able to use the backpack.
You can than control the size of their backpack with the `backpack.size.1` to `backpack.size.6` permissions.

**Comment by AndreyADeveloper** [comment]
Do I find that in the config file?

**Comment by GeorgH93** [comment]
You can find the full list of permissions in the [wiki](https://github.com/GeorgH93/Minepacks/wiki/Permissions) or the [plugin.yml](https://github.com/GeorgH93/Minepacks/blob/master/Minepacks/resources/plugin.yml).

**Comment by AndreyADeveloper** [comment]
For some odd reason, the host I'm using (MineHut) Does not have a plugin.yml file. This might be the reason why other players cannot use the backpack.

**Comment by GeorgH93** [comment]
The plugin.yml file is bundled with the plugin.
You can set the permissions in your permissions plugin. If you do not have a permission plugin you can use the permissions.yml (in your servers root dir (where the worlds and plugins folder) are located) following [this guide](https://github.com/GeorgH93/Minepacks/wiki/FAQ).

**Comment by AndreyADeveloper** [comment]
Alright, it works now, Thanks!
