### ISSUE TITLE
Attempting to connect minepacks to bungee

### ISSUE THREAD

**Issue by Bigi2** [GeorgH93/Minepacks#113]
### Help request

**Problem**

Hello! I have been trying to connect minepacks among 3 servers using MYSQL and so far haven't been successful. Whenever I put in my database details and restart the servers, all items disappear from the backpacks when moving between servers or logging off. 
I have put the plugin into my bungee server but it has not generated a folder, not sure if that is the issue. 

**What I have tried**

I've tried playing around with the config settings but the issue seems to happen when I add in MYSQL details and set bungeecord to true.

**Comment by GeorgH93** [comment]
Could you please share your log file with me?

**Comment by Bigi2** [comment]
[2020-05-19-1.log.gz](https://github.com/GeorgH93/Minepacks/files/5214055/2020-05-19-1.log.gz)

**Comment by GeorgH93** [comment]
According to this log file you don't even have Minepacks installed.

**Comment by Bigi2** [comment]
That's so weird.... because it is installed and I have access to the commands and have used them.

**Comment by Bigi2** [comment]
[latest.log](https://github.com/GeorgH93/Minepacks/files/5217946/latest.log)

**Comment by GeorgH93** [comment]
Your MySQL user does not have the "REFERENCES" privilege.

**Comment by Bigi2** [comment]
How do I adjust privileges? My database isn't allowing me to adjust them.

**Comment by GeorgH93** [comment]
If you are using the MySQL database provided by your server provider you will probably have to contact them.

If you have admin access to the database, login with your admin account and run `GRANT REFERENCES ON <YOUR_DATABASE_NAME> TO '<YOUR_USER>'@'%'; ` and then run `FLUSH PRIVILEGES;`.

**Comment by Bigi2** [comment]
[message-1.txt](https://github.com/GeorgH93/Minepacks/files/5258634/message-1.txt)
It's not a privileges problem, I have all the privileges. This is the problem that comes up in console, how do I fix it?

**Comment by GeorgH93** [comment]
You could try to create the table manually with this query:
```SQL
CREATE TABLE IF NOT EXISTS `backpacks` (
`owner` INT UNSIGNED NOT NULL,
`itemstacks` BLOB,
`version` INT DEFAULT 0,
`lastupdate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`owner`)
);
```
