### ISSUE TITLE
Could not pass event InventoryCloseEvent to Minepacks v2.3.18-Release

### ISSUE THREAD

**Issue by ImHumbug** [GeorgH93/Minepacks#114]
I get this error everytime I close the backpack https://pastebin.com/WD1rwArZ
![2020-09-20_12 50 44](https://user-images.githubusercontent.com/44101081/93715536-5291ff80-fb40-11ea-8319-a0e186ee08dd.png)

**Comment by GeorgH93** [comment]
I assume you have remove the closed message.
Please update to [this build](https://ci.pcgamingfreaks.at/job/Minepacks/231/artifact/a/Minepacks-2.3.18-Release.jar).
Or use the SendMethod option to disable the message in your language file like this:
```OwnBackpackClose: ""
OwnBackpackClose_SendMethod: "disabled"```

**Comment by ImHumbug** [comment]
oh, thanks
