### ISSUE TITLE
conflict with deadchests

### ISSUE THREAD

**Issue by snostormjp** [GeorgH93/Minepacks#115]
### Help request

**Problem**
When using on a paper-204 server with deadchests plugin the backpacks are multiplied at respawn.  A link of the backpack is in the deadchest and a new one gets made on respawn. Thee links can not be cleared or destroyed. they are links in that all backpacks point to same entry in database.

**What I have tried**
 I have tried chaging drop at death and keep inventory in config but can not get any different behaviour and while I can stack the links I can not clear them form Inventory.

**Comment by snostormjp** [comment]
I was able to clear the links if i clear the backpack

**Comment by GeorgH93** [comment]
Please try if enabling the `ImproveDeathChestCompatibility` config option solves the problem for you.
