### ISSUE TITLE
No commands are working in French

### ISSUE THREAD

**Issue by orangcrsh** [GeorgH93/Minepacks#116]
### Help request

**Problem**
I switch to "fr" in the config file of minepacks, and then the commands /bp or /backpacks are not working anymore. If I put it back to "en" then reload, the commands are working again. 

**What I have tried**
I have tried to replace the content of the fr..yml file in the en.yml but same result, no commands are working.
I have also looked arround to see that, if I change the language, may be the commands syntax will also switch language ? So I tried with "Sac" "Sac à" "Saca" "S" because "Back Pack" is "Sac à dos" in French, but no.. Really... If I begin to tape "/bp" it's in red, like if I had no rights on the pluggin.

**Comment by GeorgH93** [comment]
There is a `s` to much at the end of line 25 in the french language file. Please remove is and the plugin should work again.

**Comment by orangcrsh** [comment]
> 
> 
> There is a `s` to much at the end of line 25 in the french language file. Please remove is and the plugin should work again.

You are a genius. This must have been done with the famous "Ctrl+S" but I guess the Ctrl did not worked, lol.

It is working, nice eyes !

Thanks **_a lot_**
