### ISSUE TITLE
Question - Can we only give 1 squarre ? 2 Squarres before 1 complete row ?

### ISSUE THREAD

**Issue by orangcrsh** [GeorgH93/Minepacks#117]
### Help request

**Problem**
Hi there, I would want to know if it is possible to give only for example 1 squarre available, so it would take +9 levels to get a complete collumn.

**What I have tried**
I have tried to give 0.1 in the commands instead of 1, but it is not working.

**Comment by GeorgH93** [comment]
Will be added with the v3.0 update.
See [this issue](https://github.com/GeorgH93/Minepacks/issues/5) for reference.
