### ISSUE TITLE
Change sound when opening backpack

### ISSUE THREAD

**Issue by orangcrsh** [GeorgH93/Minepacks#118]
Hey there,

can we put a custom .mp3 or .wav in the minepacks folder to replace the chest sound it plays when we open it ?

Thank you

**Comment by Delogify** [comment]
you can play other minecraftsounds but a custom sound isnt possible without a client mod

**Comment by orangcrsh** [comment]
> you can play other minecraftsounds but a custom sound isnt possible without a client mod

I'm interested to know more, how could I play this one: https://www.youtube.com/watch?v=o8BEEy5apn4
It sounds more natural for a bag inventory opening than a... Chest sound lol

**Comment by GeorgH93** [comment]
You can play all vanilla sounds by changing the `OpenSound` and `CloseSound` config options. The sound you are referring to should be `ITEM_ARMOR_EQUIP_LEATHER`.
