### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by GeorgH93** [GeorgH93/Minepacks#12]
Add the ability to backup backpacks.
Store backpacks that have failed to save.
Add option to restore backpack.

- [x] Create backup in case of error
- [x] Add option to create backup
- [x] Add option to load backup

**Comment by SiuanSong** [comment]
Will this be for MySQL as well?

**Comment by GeorgH93** [comment]
Yes, this will also be available for all the storage providers of the plugin, including MySQL.
