### ISSUE TITLE
Failed to get driver instance 

### ISSUE THREAD

**Issue by Westloch** [GeorgH93/Minepacks#124]
originally reported as question, but it might be a bug.

Error on start up:

```
29.10 14:44:56 [Server] INFO [Minepacks] Enabling Minepacks v2.3.19-Release
29.10 14:44:56 [Server] INFO [Minepacks] Starting Minepacks in standalone mode!
29.10 14:44:56 [Server] INFO [Minepacks] Config file successfully loaded.
29.10 14:44:56 [Server] INFO [Minepacks] Language file successfully loaded. Language: english  Author: GeorgH93
29.10 14:44:56 [Server] INFO [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
29.10 14:44:56 [Server] ERROR [Minepacks] There was a problem creating the connection pool for the SQL server! Please check your configuration.
29.10 14:44:56 [Server] ERROR [Minepacks] Error: Failed to get driver instance for jdbcUrl=jdbc:mysql://~~(IP REMOVED)~~/mc72508
29.10 14:44:56 [Server] INFO [Minepacks]  Minepacks has been enabled!  :) 
```

Once in game if i reload minepacks (twice) using /backpack reload on all servers in bungee network then it works fine and i am able to use mine packs across entire network (have to reload plugin ingame across all servers first)

Once the server restarts it breaks again

Minepacks Version: 2.3.19-Release
Server: 1.16.2-R0.1-SNAPSHOT (git-Paper-189 (MC: 1.16.2))
Java: 11.0.2

**Comment by GeorgH93** [comment]
Please try if [this build](https://ci.pcgamingfreaks.at/job/Minepacks/236/artifact/a/Minepacks-2.3.20-SNAPSHOT-Release.jar) solves the problem for you.
