### ISSUE TITLE
Using the packpack by Player ! Any fixes or ideas ?

### ISSUE THREAD

**Issue by FarLokus** [GeorgH93/Minepacks#125]
Hi,

I want that the player not drag and drop the backpack  in the Inventory.

Can you give an update to allow me setting up in the config, 
that the player have an backpack at a fixed slot.

Maybe with pemissions?
- backpack.drop
- backpack.slot.*

example config.yml:
- playercandrop: true/false
# "if playercandrop is false"
- inventorrySlot: [ {0-8 or 1-9} or {0-35 or 1--36}]

For other plugins my server is using InventoryPages, too.
Maybe you can give an helpings?

example in your config.yml:
- useInventoryPages: true/false
# it meens too allow the plugin setting up pages in the backpacks inventory.

THX

**Comment by GeorgH93** [comment]
Hi,

I think what you are searching for are [these two config options](https://github.com/GeorgH93/Minepacks/blob/91da3b9073186d09e1cb80de81fc276a86c10d93/Minepacks/resources/config.yml#L186-L189).

**Comment by FarLokus** [comment]
Oh,

I've not seen.

THX
