### ISSUE TITLE
Minepacks don't work in 1.16.4

### ISSUE THREAD

**Issue by CrazyDuk** [GeorgH93/Minepacks#127]
### Information
**Environment information**
*Plugin + server version info*:

```

Unknown command. Type "/help" for help.

```

*Online mode*:  Yes

*BungeeCord*:  no

**Server/crash log**

```

None

``` 

**Plugin config (optional)**

```

Idk how to do this but config file version is 32.

```

### Details
**Description**  
The backpack plugin just does not work at all. It's just a player head and when you run the command nothing happens. I use minehut to host my server and ever since it became 1.16.4 it stopped working.

**Steps to reproduce**  
Tried to open the backpack.

**Expected behavior**  
Open the backpack

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
It happened ever since my server updated to 1.16.4. Essentials doesn't even see it as a plugin anymore on the plugin list. The files however are still there.

**Comment by DereC4** [comment]
Seems to occurring to me too

**Comment by GeorgH93** [comment]
Should be fixed with [this update](https://github.com/GeorgH93/Minepacks/releases/tag/v2.3.20).
