### ISSUE TITLE
Only OP players have BACKPACK

### ISSUE THREAD

**Issue by Skyquior** [GeorgH93/Minepacks#129]
### Help request

**Problem**
My problem is that only OP players can use the backpack. The problem is that I dont want to op everyone on the server. So is there a way to activate the plugin for every player (op and not op) ?

**What I have tried**
I tried to use the plugin PermissionEX but its a real pain to use it with all the plugins i already have. So i prefer not to. Is there another solution ? If so. If i really need to use permissionEX. What should I write in the permissionEX file to let my server know that non-op players can use the backpack too.

Thank you !

**Comment by GeorgH93** [comment]
You can use [this workaround](https://github.com/GeorgH93/Minepacks/wiki/FAQ#how-can-i-use-the-plugin-without-a-permission-plugin).

**Comment by Skyquior** [comment]
I tried this and NON-OP players can use the backpack, correct, BUT when they die, they loose all the ressources inside it. So is there a code to keep the ressources/items inside after their death ?

**Comment by Skyquior** [comment]
Its ok ! I found that I could add this line : "backpack.keepOnDeath: true" and it works now ! Thank you for your support.
