### ISSUE TITLE
how do i adjust all these settings?! 

### ISSUE THREAD

**Issue by JennerPalacios** [GeorgH93/Minepacks#13]
settings for plugin.yml... i can't find that file in my server, is it in the .jar?
my friend's can't use their backpack, only me - server admin....

**Comment by GeorgH93** [comment]
To edit the plugin.yml you have to extract the file from the plugin jar with an archival program like 7zip or winrar. Extract the file, edit it, put it back in the archive. However you will have to do this chances every time there is an update for the plugin.

If you just would like to give others the permission to use the backpack there is a better way.
You can use bukkit's build in permission manager to give out the permissions. https://bukkit.gamepedia.com/Permissions.yml
Just create a text file named "permissions.yml" next to your servers jar file and put something like this in it:
`server.basics:
  default: true
  children:
    backpack: true
    backpack.size.6: true`
