### ISSUE TITLE
Minepacks is crashing my server

### ISSUE THREAD

**Issue by joeyk710** [GeorgH93/Minepacks#132]
### Information
**Environment information**
*Plugin + server version info*:

```


<!-- [Wed, 11. Nov 2020 12:53:27 EST INFO] ##### Start Minepacks version info #####
       [Wed, 11. Nov 2020 12:53:27 EST INFO] Minepacks: 2.3.20-Release
       [Wed, 11. Nov 2020 12:53:27 EST INFO] Server: git-Paper-267 (MC: 1.16.4)
       [Wed, 11. Nov 2020 12:53:27 EST INFO] Java: 1.8.0_212-1-ojdkbuild
       [Wed, 11. Nov 2020 12:53:27 EST INFO] #####  End Minepacks version info  ##### -->

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

<!-- [latest.log](https://github.com/GeorgH93/Minepacks/files/5525851/latest.log) -->

```

**Plugin config (optional)**

```

<!-- -->

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
I'm sorry, but I do not see any error related to Minepacks in that log.

**Comment by joeyk710** [comment]
Alright. Thanks for looking at it!
