### ISSUE TITLE
Unsupported database backend | MySQL

### ISSUE THREAD

**Issue by dweSheppard** [GeorgH93/Minepacks#133]
### Information
**Environment information**
*Plugin + server version info*:

```

> backpack version
[10:45:48 INFO]: Only "/backpack reload" is available at the moment!
(plugin: 2.3.20, server: git-Paper-265 (MC: 1.16.4), java: version "1.8.0_265")

```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**

```

https://pastebin.com/puDuHVcD

```

**Plugin config (optional)**

```

https://pastebin.com/JjWWC4EJ

```

### Details
**Description**  
The error has occurred since the update to 1.16.4

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Please try if adding [this](https://ci.pcgamingfreaks.at/job/PluginLib/455/artifact/target/PCGF_PluginLib-1.0.30-SNAPSHOT.jar) to your plugins solves the problem for you.

**Comment by dweSheppard** [comment]
It works. thank you :)
