### ISSUE TITLE
Warn in the console 1.14.4

### ISSUE THREAD

**Issue by RE4ERKA** [GeorgH93/Minepacks#134]
### When starting or reloading the server, the console displays this error:
![image](https://user-images.githubusercontent.com/66727581/99149586-94af6b80-26c1-11eb-8d3b-aa528d4cf80d.png)
At the same time, the plugin works stably, but the error interferes. If the problem is on my side, let me know what to do and sorry for the trouble. If not, please correct it.
Server core: PaperSpigot 1.14.4
Plugin version: 2.3.20

**Comment by GeorgH93** [comment]
Should be fixed with [this update](https://github.com/GeorgH93/Minepacks/releases/tag/v2.3.21).
