### ISSUE TITLE
Could you expose Minepacks#isDisabled(Player)?

### ISSUE THREAD

**Issue by SHsuperCM** [GeorgH93/Minepacks#135]
### Feature request

**Feature description**
Could you please expose to the API `Minepacks#isDisabled(Player)` and WorldBlacklistMode?

**How the feature is useful**
It will help achieve consistency with other plugins wanting to reuse Minepacks' configuration to apply custom rules and features to backpacks.

**Comment by GeorgH93** [comment]
Will be available with v2.3.21.1
