### ISSUE TITLE
Is there a way to disable bp for specific worlds?

### ISSUE THREAD

**Issue by EvanAlexJames** [GeorgH93/Minepacks#14]
I am using multiverse and my players are currently able to use the back pack in creative and bring the items back into survival with them. Is there a way to disable this? If not, can there be?

**Comment by GeorgH93** [comment]
You can use your permission plugin to do this (e.g. for pex: /pex group default add -backpack.* creative_world)

You can also use the " allowed_game_modes" config option to limit the use to survival or whatever you like.
`allowed_game_modes：[“SURVIVAL”]`
or
`allowed_game_modes：[“SURVIVAL”, "ADVENTURE"]`

**Comment by GeorgH93** [comment]
Extended support to disable the plugin in certain worlds will be added with V2.0.
https://github.com/GeorgH93/Minepacks/issues/16
