### ISSUE TITLE
Blacklist feature seems to be broken.

### ISSUE THREAD

**Issue by MrPajamaLlama** [GeorgH93/Minepacks#141]
I have tried to use the blacklist feature, and at first glace it seems to work fine.

I blacklisted the Elytra item, and I had a player test it for me to see if it worked. When the player put the item in his 54 slot pack, all of his items dumped on the ground (lol). However, after that he opened his backpack again to see that only 9 slots were now available, and he was also able to place the elytra in his pack. The blacklist seems to only work once, after that it does not. An added issue is the fact that the backpack turned itself into a 9 slot pack when it was a 54 slot pack before.

**Comment by GeorgH93** [comment]
Please share some more information with me.

1. Output of `/backpack version`
2. Your plugin config
3. Used permission plugin + version
4. List of all installed plugins
