### ISSUE TITLE
Data lost on server restart

### ISSUE THREAD

**Issue by ImHumbug** [GeorgH93/Minepacks#146]
Minepacks: 2.3.21.2-Release
Server: git-Tuinity-"4634206" (MC: 1.16.5)
Java: 11.0.9.1

Hi my users are constantly reporting lost of items that they moved in/out backpacks near server restarts, even in some cases items got duped. Not sure if it's fault of the plugin. Could you check save behaviour on server restarts?

**Comment by GeorgH93** [comment]
Please share your log file with me.

**Comment by ImHumbug** [comment]
https://pastebin.pl/view/2259018e

**Comment by GeorgH93** [comment]
Can you please provide the rest of the log too? This only contains the shutdown sequence.

**Comment by pacificminer** [comment]
My users are reporting this as well.

If it helps I am using MySQL as storage option and BungeeCord setting enabled.

**Comment by GeorgH93** [comment]
I need the full server log to be able to diagnose this. Preferable the log from when the player last used the backpack till the point where it was discovered that the items are missing.
