### ISSUE TITLE
clear from console entirely

### ISSUE THREAD

**Issue by victoryneM** [GeorgH93/Minepacks#149]
### Information
**Environment information**
*minepack 2.3.21 + paper 409 + mc 1.16.4*:

minepack 2.3.21 

minepack 2.3.21 

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  

I have a deluxe menu with such commands : 
right_click_commands:
      - "[console] clear %player_name% carrot 1728"
 When i installed minepack, this command clear all the inventory.

**Steps to reproduce**  

I had 1728 carrot in my inventory and other stuff, all my inventory has been cleared when I execute the cammnd of the menu (/coupons)

**Expected behavior**  

It should have clear only 1728 carrots

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Minepacks has it's own inventory clear command. You can disable it in the config under `InventoryManagement.ClearCommand.Enabled`.
