### ISSUE TITLE
Backpack size is either 1 or 6

### ISSUE THREAD

**Issue by VikkTheNest** [GeorgH93/Minepacks#152]
Hello!
I would like to set a 3 row backpack for all my friends on the server. However, I tweaked every combination and option for the sizes and the result is always a 1 or 6 row size. I even tried to change the **backpack.use** permission to **backpack**. I read about another issue similar to this and set the max size over 6, but it didn't work either. Anyways this would be a great plugin, I'd be really happy to solve this problem. 

![image](https://user-images.githubusercontent.com/79048943/107879070-f953af80-6ed6-11eb-858d-fc2039f04672.png)

**Comment by GeorgH93** [comment]
Looks like the server is picking on of the other permission groups up for op's. if you add `backpack.size.6: false` to your permissions or change the `MaxSize` option to 3 it should work.

**Comment by VikkTheNest** [comment]
I did both and it still doesn't wanna work. :( I even put the backpack permissions into a new group. Maybe I'll tryna change the **default** from **op** to **true** and assign them to the whitelist players one by one, that's the last thing that came to mind. 
Nevertheless the other features are flawless so I just left it on 6 row rather than 1. Thank you though, cute great plugin!
