### ISSUE TITLE
Backpack double if you die

### ISSUE THREAD

**Issue by Luxis-light** [GeorgH93/Minepacks#153]
It comes in Trouble with the the plugin Deadchest and if you die you will get two backpacks 
(I need the Entity name for the backpack)

**Comment by GeorgH93** [comment]
Please try if the `ImproveDeathChestCompatibility` config option solves the issue for you.

**Comment by Luxis-light** [comment]
thx but what can i do to delet the other one ?

**Comment by GeorgH93** [comment]
The duplicates should get removed automatically after reconnecting, switching world or re-spawning.

**Comment by ErythroCraft** [comment]
Sry for this.

You can use the minecraft command /replaceitem
See here:
https://minecraft-de.gamepedia.com/Befehl/replaceitem
