### ISSUE TITLE
How do I use

### ISSUE THREAD

**Issue by HLC2** [GeorgH93/Minepacks#155]
How can have others use the plugin without having op because right now you need op to use the plugin

**Comment by GeorgH93** [comment]
You have to give your players the `backpack.use` permission. Also you should give them one of the size permissions `backpack.size.1`, `backpack.size.2`, `backpack.size.3`, `backpack.size.4`, `backpack.size.5` or `backpack.size.6`.
If you do not have a permission plugin please check this link: https://github.com/GeorgH93/Minepacks/wiki/FAQ#how-can-i-use-the-plugin-without-a-permission-plugin

**Comment by HLC2** [comment]
> You have to give your players the `backpack.use` permission. Also you should give them one of the size permissions `backpack.size.1`, `backpack.size.2`, `backpack.size.3`, `backpack.size.4`, `backpack.size.5` or `backpack.size.6`.
> If you do not have a permission plugin please check this link: https://github.com/GeorgH93/Minepacks/wiki/FAQ#how-can-i-use-the-plugin-without-a-permission-plugin

I'm pretty new to making servers how can I let players I use that command?

**Comment by GeorgH93** [comment]
Open the `permissions.yml` file (in the same folder as the server jar and the plugins directory) and paste this into it:
```yaml
minepacks:
  default: true
  children:
    backpack.user: true
    backpack.size.6: true
```
