### ISSUE TITLE
Ignore Citizens player NPCs

### ISSUE THREAD

**Issue by Henriiig** [GeorgH93/Minepacks#156]
### Feature request

**Feature description**

This may actually be a bug but I would like to have the plugin to ignore player npcs created by citizens because everytime a NPC dies the console tells me that a backup of the npcs backpack was created because it ran into an errorr.

**How the feature is useful**

Explained above

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/247/artifact/a/Minepacks-2.3.21.3-Release.jar).
