### ISSUE TITLE
Backpack shortcut does not appear for my server members

### ISSUE THREAD

**Issue by Dieg0x** [GeorgH93/Minepacks#158]
Only me and the admins have the backpack in inventory, but the other members do not, how can it be fixed?

**Comment by GeorgH93** [comment]
You have to give your players the `backpack.use` permission. Also you should give them one of the size permissions `backpack.size.1`, `backpack.size.2`, `backpack.size.3`, `backpack.size.4`, `backpack.size.5` or `backpack.size.6`.
If you do not have a permission plugin please check this link: https://github.com/GeorgH93/Minepacks/wiki/FAQ#how-can-i-use-the-plugin-without-a-permission-plugin
