### ISSUE TITLE
Backpack's space

### ISSUE THREAD

**Issue by borjxrroyo** [GeorgH93/Minepacks#159]
### Information
**Environment information**
*Plugin + server version info*:

```

https://i.gyazo.com/223a6ca981d72c3b0bf57b573f9158c1.png

```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**
None

**Plugin config (optional)**
Defines the max amount of columns for a backpack.
The size of the user's backpack will be defined by the permission, permissions for bigger backpacks than this value will be ignored.
Can be set to anything > 0. Backpacks with more than 6 columns will have a broken UI! Sizes bigger than 9 may not work with all permission plugins.
MaxSize: 9
```

```

### Details
**Description**  
I have backpack.size.6 assigned to all players so they can have a double virtual chest, but they only see a 1-row inventory.
![image](https://user-images.githubusercontent.com/72812865/113729882-b1dbe980-96f7-11eb-9c8c-13226530ae84.png)

**Expected behavior**  
https://i.gyazo.com/775dfa717dafaa1af5f134bf5465d737.png

**Comment by borjxrroyo** [comment]
PD: Mods can't open other player's backpacks, even they have the permission.

https://i.gyazo.com/282f3313f9eaf265d0f2ecc0691d179a

https://i.gyazo.com/282f3313f9eaf265d0f2ecc0691d179a.png

**Comment by GeorgH93** [comment]
Which permission plugin are you using?

**Comment by borjxrroyo** [comment]
Luckperms

**Comment by GeorgH93** [comment]
Please run this command and share the output with me: `/lp tree backpack <playername of an online player that does not have the correct bp size>`

**Comment by borjxrroyo** [comment]
Even if they don't have permissions to open the backpack right now, I think it should work (the size).

https://i.gyazo.com/c8544598afc87563076f44ca14761601.png
https://i.gyazo.com/8316c8c743c0ddcd7791019b73f93541.png

**Comment by GeorgH93** [comment]
Could you please rerun the command on someone that has the permission to open it.

**Comment by borjxrroyo** [comment]
Same output, but backpack.use is true

**Comment by GeorgH93** [comment]
I am sorry, I am unable to reproduce this.
Can you please share the list of installed plugins and your luckperms permission config with me, so that I can perform more in-depth testing.

**Comment by borjxrroyo** [comment]
Np, I could solve it. I was lacking the permission node backpack.use

The backpacks got their normal size when opened by the players.
