### ISSUE TITLE
Please add an option to see if player already has a backpack

### ISSUE THREAD

**Issue by flololan** [GeorgH93/Minepacks#160]
We have a Paper server with DeadChests and Minepacks. Our problem is, that all Items including the backpacks get put into the deadchest when the player dies. As the player gets a new Backpack on respawn, the number of backpacks increases with each death (after picking up the DeathChest). 
Throwing away the backpacks is not possible even though  I have 10 by now. 

It would be nice to add a either a possibility to throw away the backapacks (if there is more than one in inventory) or to give an option to deactivate new backpacks on respawn.

**Comment by GeorgH93** [comment]
Please enable the `ImproveDeathChestCompatibility` config option.
Also if you stack them up the additional copies should be removed when you join or switch world the next time.

**Comment by flololan** [comment]
whoops, i missed that one. sorry and thank you!
