### ISSUE TITLE
Backpacks can be moved with off-hand

### ISSUE THREAD

**Issue by hexagon02** [GeorgH93/Minepacks#162]
Hello,
I configurated the config.yml with "BlockAsHat: true" and "BlockItemFromMoving: false".
Players cannot drop the backpack item shortcut with "Q" and they can't use it as a hat.
But there is a bug: if they press "F" holding a backpack in their hand, then it is moved to their off-hand. Then, if they press "F" again while pointing the cursor on a chest slot or even on the helmet slot, then the backpack is moved there. It results in the possibility to duplicate the backpack item shortcut unlimited times, and it is a really bad thing for gameplay...
Is there a way to fix it?
Thank you!

**Comment by GeorgH93** [comment]
Fixed with [this release](https://github.com/GeorgH93/Minepacks/releases/tag/v2.3.24).
