### ISSUE TITLE
MC 1.17 Support

### ISSUE THREAD

**Issue by BugCode1** [GeorgH93/Minepacks#167]
It's time to mc 1.17 update ...

**Comment by GeorgH93** [comment]
Minecraft 1.17 has been released. This plugin needs to be updated.

**TODO:**
- [ ] [Update PCGF PluginLib to MC 1.17](https://github.com/GeorgH93/PCGF_PluginLib/issues/20)
- [ ] Testing

**Comment by BugCode1** [comment]
So Fast 😉 I'm going to test that right now

**Comment by BugCode1** [comment]
Running on Release build wihtou PCGF PluginLib, It's work and not have any problem 👍
