### ISSUE TITLE
cannot pickup items after opening the backpack.

### ISSUE THREAD

**Issue by ImHumbug** [GeorgH93/Minepacks#174]
Video: https://fuze.tv/elzu96/post/60e71787cb798f00166d80a6
Plugin version: 2.4.1-Release
Server Version: This server is running Airplane version git-Airplane-43 (MC: 1.17.1)

**Comment by GeorgH93** [comment]
What is Airplane? Where can I get this for testing?

looks like you are picking the items up, but the UI is not refreshing correctly.

**Comment by ImHumbug** [comment]
https://airplane.gg
From waht I've known a very stable fork, also it's implemented by default on purpur.

**Comment by jw-taylor** [comment]
I also have this on PaperMC. This is what I put on the Spigot page:

> We're having an issue where after opening and closing the backpack, your inventory doesn't update e.g. I start cutting down trees with an axe in my hotbar but nothing else, and the axe's durability doesn't go down and the logs/sticks etc. I'm picking up don't appear in my hotbar - and when the axe breaks I hear the breaking noise but it's still in my hand, and I can use it to destroy a log block quickly but the block reappears. I have to then go into my inventory and click on the backpack icon to make my inventory refresh. This doesn't happen if I use the command /backpack
> 
> EDIT: Bit more info: when you open your inventory for the first time after closing the backpack, the backpack icon is duplicated and stuck to your cursor and the only way to get rid of it is to right-click in your inventory. That's when the inventory refreshes.
> 
> EDIT 2: Here's a video demonstrating what I mean. https://streamable.com/z4lzql
> 
> I'm running the latest version of the mod on PaperMC 1.17.1

**Comment by GeorgH93** [comment]
Should be fixed with [this release](https://github.com/GeorgH93/Minepacks/releases/tag/v2.4.2).
