### ISSUE TITLE
A new traditional Chinese language is added, and there are files translated by myself in the article.

### ISSUE THREAD

**Issue by Special-Base** [GeorgH93/Minepacks#175]
### Feature request

**Feature description**
Add a traditional Chinese language that I translated.

**How the feature is useful**
Make it more convenient for some players who use traditional Chinese

This is using Google drive
[https://drive.google.com/file/d/1pxpEMeXZnM9GT3GOXk-_-J1aT1ocaVha/view?usp=sharing](https://drive.google.com/file/d/1pxpEMeXZnM9GT3GOXk-_-J1aT1ocaVha/view?usp=sharing)

**Comment by GeorgH93** [comment]
Thanks for sharing. Will be added in the next update.
