### ISSUE TITLE
MySQL connect error

### ISSUE THREAD

**Issue by XiaoNiuC** [GeorgH93/Minepacks#177]
server version: Purpur version git-Purpur-1350 (MC: 1.17.1)
plugin version: Minepacks: 2.4.2-Release

BungeeCord Online mode

Server Log: https://gist.github.com/XiaoNiuC/2cdf3121792a919435d7082eff314197

Plugin Config: https://gist.github.com/XiaoNiuC/682d81f50c0cd69db8dd493fac3df48d

I use this plugin on BungeeCord and everything worked fine a few days ago
But the error suddenly started to happen yesterday
Many players input /bp to open the backpack then data is abnormally lost, and not all players have backups
This troubles me a lot, how can I solve it? 

In addition, even if you do not enter /bp, this warning will pop up when you log in to the server
`[Mon, 27. Sep 2021 07:56:57 CST WARN] Minepacks-Connection-Pool-Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@25f2ce93 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.`

**Comment by GeorgH93** [comment]
Looks like for some reason the plugin is no longer able to communicate with your MySQL server. Are you sure your MySQL server is still running and reachable?
The lost data should still be there, the plugin will automatically backup the data if it fails to write them to the database. You can use `/bp restore list` to get a list of all created backups. You should be able to restore them by clicking on them.

**Comment by XiaoNiuC** [comment]
Understand, it seems that there was a problem with my database at the time
Thank you for your reply!
