### ISSUE TITLE
Bad config file version

### ISSUE THREAD

**Issue by FastJoe0** [GeorgH93/Minepacks#18]
04.05 12:48:41 [Server] INFO [MinePacks] Enabling MinePacks v1.17.7
04.05 12:48:41 [Server] INFO [MinePacks] Configuration Version: 15 => Configuration outdated! Upgrading ...
04.05 12:48:41 [Server] INFO [MinePacks] No config found. Create new one ...
04.05 12:48:41 [Server] INFO [MinePacks] Configuration extracted successfully!
04.05 12:48:41 [Server] INFO [MinePacks] Configuration has been updated.
04.05 12:48:41 [Server] INFO Minepacks-Connection-Pool - is starting.
04.05 12:48:42 [Server] INFO [MinePacks] MinePacks has been enabled!

**When I manually change the version to 16, the error doesn't occur.:**

```
# Config file version. Don't touch it!
Version: 16
```

04.05 12:52:07 [Server] INFO [MinePacks] Enabling MinePacks v1.17.7
04.05 12:52:07 [Server] INFO Minepacks-Connection-Pool - is starting.
04.05 12:52:08 [Server] INFO [MinePacks] MinePacks has been enabled!

**Comment by GeorgH93** [comment]
Fixed. Update available: https://dev.bukkit.org/projects/minepacks/files/2558313/download
