### ISSUE TITLE
Item dupes when spread out

### ISSUE THREAD

**Issue by Spartac69** [GeorgH93/Minepacks#186]
![image](https://user-images.githubusercontent.com/87254357/142828844-ca284454-c437-4b07-8ffb-bb995ac5a2b7.png)
When your inventory is spread out full like that and you pick up an item, the feature of when your inventory is full and it goes in your backpack makes it so it dupes the item making it go into the backpack and your inventory

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/273/artifact/a/Minepacks-2.4.3-RC3-Release.jar).
