### ISSUE TITLE
Change text for "backpack closed" pop up

### ISSUE THREAD

**Issue by Tabletopcheese** [GeorgH93/Minepacks#187]
### Feature request

**Feature description**

Text edit for "backpack closed

**How the feature is useful**

On my server and others, we change the player head to another item . Example. A wallet.

**Comment by GeorgH93** [comment]
You can change all messages in the language file `plugins/Minepacks/lang/<language, e.g. en>.yml`.

**Comment by Tabletopcheese** [comment]
Thank you so much for the support. I can't believe I missed that.
