### ISSUE TITLE
Dutch language file submission

### ISSUE THREAD

**Issue by bramvkempen** [GeorgH93/Minepacks#19]
I have made a Dutch language file. I would appreciate it if you would add it to the plugin. I have added it as an attachment.

Greetings from,
bramvkempen

[nl.zip](https://github.com/GeorgH93/Minepacks/files/1976868/nl.zip)

**Comment by GeorgH93** [comment]
Thanks, I have added it https://github.com/GeorgH93/Minepacks/commit/5e281241a6d84c782eec860735024a92c0488f91
