### ISSUE TITLE
cooldown support for multiple servers

### ISSUE THREAD

**Issue by helptiger** [GeorgH93/Minepacks#2]
hey, I'm using this pl on a bungeecord network, so the players have access to their backpacks on multiple servers. Also I have a cooldown for access to the bp – but if the player switches the server – he could access the bp directly.
Is it possible to sync the cooldown or alternative add a login cooldown? thx

**Comment by GeorgH93** [comment]
hey, I have added an option to add a cooldown for every player that joins the server. I will add an sync option on a later point.
You can find the newest point here: https://ci.pcgamingfreaks.at/job/Minepacks/11/artifact/target/MinePacks-1.16.4.2-SNAPSHOT.jar

**Comment by helptiger** [comment]
java.lang.NoClassDefFoundError: at/pcgamingfreaks/Bukkit/Utils
http://pastebin.com/fQqSWua4

**Comment by GeorgH93** [comment]
Is fixed now: https://ci.pcgamingfreaks.at/job/Minepacks/13/artifact/target/MinePacks-1.16.4.2-SNAPSHOT.jar
Sorry for the inconvenience.

**Comment by GeorgH93** [comment]
Syncing cooldowns between multiple servers has been added to V2.0: https://github.com/GeorgH93/Minepacks/commit/09cd1a0fb2bf0dd255f25e11dbcc26b8e52fa98f
