### ISSUE TITLE
HEX Support

### ISSUE THREAD

**Issue by iTzAleh** [GeorgH93/Minepacks#201]
It is possible to use HEX color format?

**Comment by GeorgH93** [comment]
Yes, you can either format the message as JSON or use &x&R&R&G&G&B&B or &xRRGGBB.
Please note that rgb colors in players display name are currently not handled correctly (I am working on it).

**Comment by iTzAleh** [comment]
for example can I use this color (&#a52a2a)? how?

**Comment by GeorgH93** [comment]
`&xa52a2a` or `&x&a&5&2&a&2&a`

**Comment by iTzAleh** [comment]
thank you ❤️
