### ISSUE TITLE
Upgrade to 1.18.2 from 1.18.1 backpacks not working

### ISSUE THREAD

**Issue by jackaboy216** [GeorgH93/Minepacks#204]
### Help request

**Problem**
The plugin doesn't work anymore and i'm trying to find where the items that are in a players backpack are in the files so i can get them back cause i can't down garde the mc version
 

**What I have tried**
I have looked in the server files where the plugin is stored and the minepacks folder but i can't find it

**Comment by GeorgH93** [comment]
Update for 1.18.2 will be available later today.
To protect the data, Minepacks will only run on versions that I have fully tested.

If you like, you can try the prerelease build form here. (Please create a backup before using this version).


Where the backpacks are stored depends on your config. By default, they are stored in the backpack.db file.

**Comment by jackaboy216** [comment]
Okay thank you!

**Comment by GeorgH93** [comment]
Update for 1.18.2 has been released on spigot.
