### ISSUE TITLE
SQLite to MySQL migration

### ISSUE THREAD

**Issue by disqetow** [GeorgH93/Minepacks#21]
How tp change SQLite data to mysql?

**Comment by GeorgH93** [comment]
There currently is no way to migrate data from one storage format to another.
I will add an option for that soon.

**Comment by GeorgH93** [comment]
Database migration is now available in Minepacks V2.0 beta builds.

You can find the Minepacks V2.0 beta builds here: https://ci.pcgamingfreaks.at/job/Minepacks%20V2/
Minepacks V2.0 requires an additional library which can be found here: https://ci.pcgamingfreaks.at/job/PluginLib/
The manual for using the migration feature can be found here: https://github.com/GeorgH93/Minepacks/wiki/Migration-Manual
