### ISSUE TITLE
Giving backpacks after they already have one

### ISSUE THREAD

**Issue by LGLLewis** [GeorgH93/Minepacks#214]
### Help request

**Problem**
Whenever someone joins the server even if they have joined before it will give them a new backpack so they are having like 5 of them in their inv

**What I have tried**
I have turned off the give on join part and it still gives them a new one. Im wanting it to only give them one if they dont have one already

**Comment by GeorgH93** [comment]
Have you changed the `ItemName` config option? If so, to what?

Also, whats the output of `/backpack version`?

**Comment by GeorgH93** [comment]
Please change the item name to `"&e&l&k!&bBackpack&e&l&k!&r"`. Then it should work.

**Comment by LGLLewis** [comment]
> 

thats what i did in the first place

**Comment by GeorgH93** [comment]
So switching the l and k did not fix it for you?
