### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by crazynerdpc** [GeorgH93/Minepacks#216]
the 1.19 update has came out and i dont see minepacks. its one of my favorites! plz update!

**Comment by GeorgH93** [comment]
The spigot update has just released 2h ago.
There will be an update for the plugin once I have updated everything to work with the new version.
Please be patient.

**Comment by crazynerdpc** [comment]
Thank you Sent from Mail for Windows From: GeorgH93Sent: Tuesday, June 7, 2022 1:15 PMTo: GeorgH93/MinepacksCc: crazynerdpc; AuthorSubject: Re: [GeorgH93/Minepacks] 1.19 (Issue #216) The spigot update has just released 2h ago.There will be an update for the plugin once I have updated everything to work with the new version.Please be patient.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by GeorgH93** [comment]
[Beta version with 1.19](https://ci.pcgamingfreaks.at/job/Minepacks/lastSuccessfulBuild/artifact/a/Minepacks-2.4.6-beta-Release.jar) support is now available.
Please backup your data before using it.

**Comment by nqaminecraft** [comment]
Hey GeorgH93, Appreciate all of your work in this plugin.

**Comment by hybridphreak** [comment]
> [Beta version with 1.19](https://ci.pcgamingfreaks.at/job/Minepacks/lastSuccessfulBuild/artifact/a/Minepacks-2.4.6-beta-Release.jar) support is now available. Please backup your data before using it.

Unfortunately the link didn't work for me, however I managed to find it [HERE ](https://ci.pcgamingfreaks.at/job/Minepacks/lastBuild/artifact/a/Minepacks-2.4.6-Release.jar) with the Dev builds, and it works great.

Really appreciate such a swift update. All working great.

Thank you!
