### ISSUE TITLE
How to reset everyone's Backpack ?

### ISSUE THREAD

**Issue by FlyingCow32** [GeorgH93/Minepacks#220]
Hey i would like to know how reset everyone's backpack ? I don't want to delete important data file so im askin first ^^'

**Comment by GeorgH93** [comment]
That depends on the storage backend used (`Database.Type` config option).

SQLite (default): delete the `backpack.db` file in the plugins data directory
MySQL: delete the `backpacks` table from your database
Files: delete the `backpacks` folder in the plugins data directory

**Comment by FlyingCow32** [comment]
okay , thanks !
