### ISSUE TITLE
Additional Backpacks

### ISSUE THREAD

**Issue by Avixius** [GeorgH93/Minepacks#222]
### Information
**Environment information**
Minepacks: 2.4.6.1 - Release

```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*: Yes

**Plugin config (optional)**
I have this plug-in and graves.

https://www.spigotmc.org/resources/gravestonesplus.95132/

```

### Details
**Description**  
When a player dies and you use the grave you get another backpack. So I have a stack of backpacks that are all the same thing and I can't get rid of the others. I'm kinda dumb so I might be missing something?

**Comment by GeorgH93** [comment]
Please enable the `ImproveDeathChestCompatibility` config option.
