### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Insidi0usAngel** [GeorgH93/Minepacks#226]
### Information
**Environment information**
*Plugin + server version info*:
![version](https://user-images.githubusercontent.com/99332317/183122746-6373a641-2d6f-4e01-9107-74b7d5bf794e.jpg)

v2.4.8-Release
Errors occurred a few days ago after getting a prompt on spigot that there was a new version - as per the console message this version claims to be 2.4.8 and today I note that on spigot it claims most recent version was 2.4.7 ? Previous version of Minepacks before updating it I had no console errors and the plugin was not disabling itself on startup.

*Online mode*: Yes

*BungeeCord*: No

**Server/crash log**
https://pastebin.com/mkw093Bq

**Plugin config (optional)**
https://www.dropbox.com/s/eyxv1lo6350rn42/config.yml?dl=0

### Details
**Description**  
Console errors
I think the error in console occurred immediately after I made the last spigot download, it is weird that the version number in config is not same as number listed on spigot.... Most of the errors in console say there are yaml errors, but i don't think I editted the settings in this plugin for a while - the last thing I did with minepacks was to use luckperms to disable /backpacks.use type commands in a new world I am building whilst making sure it can be used in all the regular worlds.

**Steps to reproduce**  
Download latest version from Spigot and use with MC 1.19 paper....

**Expected behavior**  
That backpacks should not be disabled on loading/no console errors/ backpacks should work in all allowed worlds.

**Other information** I am considering next seeing if i can download a previous version to get backpacks operational on my server in the short term.

**Comment by Insidi0usAngel** [comment]
So for me to fix this issue, using an old version of minepacks did not fix the issue, an online yaml editor said the config was valid.... But to fix this issue I then next renamed the config so that the plugin would generate a new one and now it works - so I am not sure how the config got corrupted, I am hoping now once I edit it back to incorporate my customisations it will still work...

**Comment by GeorgH93** [comment]
Your config file is missing the `#` at the start of line 165.

As to the version number, looks like i mistakenly incremented it twice. :D Have updated it on spigot.
