### ISSUE TITLE
appear another backpack in my inventory after dying

### ISSUE THREAD

**Issue by zDavidOp** [GeorgH93/Minepacks#227]
### Help request

**Problem**
Hello, I have a problem which is, when I die with a backpack it stays in the tomb that I have configured, but when spawning another backpack appears in my inventory and it is duplicated because one backpack is in the tomb and the other is in my inventory

**What I have tried**
I tried to disable backpack drop to the grave but I want the backpack to stay in the grave and not in my inventory

**Comment by GeorgH93** [comment]
Currently the only real fix is the enable the `ImproveDeathChestCompatibility` config option, it will remove the backpack from the grave.
Since the backpacks are a separately handled inventory, there currently is not way to pack them into graves, it's however planned for the future.
