### ISSUE TITLE
how do i give permissions to players

### ISSUE THREAD

**Issue by pro14812345** [GeorgH93/Minepacks#228]
### Help request

**Problem**

I have installed this plugin on my aternos server and only admins can open their backpacks, how do I fix it?
**What I have tried**

I added these permission to groups/default on luckperms:
backpack
backpack.use
backpack.sort
backpack.size.3
backpack.keepondeath

**Comment by pro14812345** [comment]
and also don't look at my name

**Comment by pro14812345** [comment]
can you just make the plugin be usable for players who don't have permissions? like I watched some YouTube videos about this plugin and I did everything they said I don't know why it doesn't work I literally gave players those permissions and that doesn't work

**Comment by GeorgH93** [comment]
You can try [this](https://github.com/GeorgH93/Minepacks/wiki/FAQ#how-can-i-use-the-plugin-without-a-permission-plugin).
Since it is most likely an issue with how you have set up luckperms please share your luckperms config.

**Comment by pro14812345** [comment]
[config.yml.txt](https://github.com/GeorgH93/Minepacks/files/9438617/config.yml.txt)
and also in aternos there is no permissions.yml or maybe it's hidden but I can't access it
