### ISSUE TITLE
Bug: backpack.keepondeath is keeping ALL inventory

### ISSUE THREAD

**Issue by k0nker** [GeorgH93/Minepacks#23]
PaperSpigot 1.13.

When a player has the permission `backpack.keepondeath` it is keeping their regular inventory as well as the backpack.  I believe this is only supposed to keep the backpack inventory.

From [SpigotMC](https://www.spigotmc.org/resources/minepacks-backpack-plugin-mc-1-7-1-12.19286/) page with permissions descriptions.
![image](https://user-images.githubusercontent.com/6345469/43664179-9d10ebb8-9731-11e8-8a1e-daad0474cb6f.png)

**Comment by k0nker** [comment]
Latest update seems to make keepondeath always active, even when set to false manually. When plugin is loaded players are keeping inventories and bp on death no matter what the setting is, even if it is undefined.

**Comment by GeorgH93** [comment]
Please try if this build resolves the issue for you: https://ci.pcgamingfreaks.at/job/Minepacks/68/artifact/target/MinePacks-1.17.13-SNAPSHOT.jar
If not please provide me with a list, of the plugins that you have installed.

**Comment by BluDragyn** [comment]
This is still persisting for me
