### ISSUE TITLE
don't deliver backpacks to non admins or new users

### ISSUE THREAD

**Issue by mauroguanaco** [GeorgH93/Minepacks#231]
sorry i don speak english.
when new users enter the server, they do not have the backpack item, supposedly it is configured so that yes:
ItemShortcut:
  # If enabled the players will be given an item they can interact with to open the backpack.
  # The item may not be removed from their inventory as long as this option is enabled.
  Enabled: **true**
  
  I think it's only for admins the item in the inventory :( and I want everyone to have the item, including non-administrators.
  I want help, sure it's very easy but I don't know.
  thank U and greetings from Argentina.

**Comment by GeorgH93** [comment]
Your users need to have the `backpack.use` permission in order to be able to use the plugin. If you don't have a permission plugin you can check [this](https://github.com/GeorgH93/Minepacks/wiki/FAQ#how-can-i-use-the-plugin-without-a-permission-plugin).
