### ISSUE TITLE
How to restore lost inventory

### ISSUE THREAD

**Issue by thiangm** [GeorgH93/Minepacks#233]
### Help request

**Problem**
Restore lost inventory

**What I have tried**
A player of my server, died by mistake and had a lot of stuff in his backpack. I would like to recover and return them, but I have checked the backup files and there is no record. Is there any way to restore the lost items?

**Comment by GeorgH93** [comment]
I am afraid, if the player died there is no way to get the items back, other then the player collecting them manually.
Backups are only created manually by an admin or if the plugin detects that the backpack could not be loaded or saved correctly.

**Comment by thiangm** [comment]
Hi, @GeorgH93 this problem has been fixed.
