### ISSUE TITLE
Problem with autopickup

### ISSUE THREAD

**Issue by Kamikazepazzo** [GeorgH93/Minepacks#237]
i have a problem with autocollect cause i try everithing but not work, and don't collect stuff when i have fulll inventory, may you help me?

### Information
**Environment information**
*Plugin + server version info*:

```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Should be fixed with [this release](https://github.com/GeorgH93/Minepacks/releases/tag/v2.4.10).

**Comment by Kamikazepazzo** [comment]
thanks but now give this error, an internal error when try to use the tab to see the command, can you do something?

**Comment by GeorgH93** [comment]
Which error? Do you have a log entry for me?

**Comment by Kamikazepazzo** [comment]
How I can send the log here? Cause I don’t know how to send the log here, When I write backpack and I press tab to see the command list, say that for an internal error can’t display the tab information. If you explain me how to send I try

**Comment by GeorgH93** [comment]
You can either drag and drop the log file onto the comment box to upload it.
Or just copy paste the relevant part of the log into the comment box.

**Comment by Kamikazepazzo** [comment]
here the log, in the last part the error when i try to use tab
[latest (8).log](https://github.com/GeorgH93/Minepacks/files/10200617/latest.8.log)

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/lastSuccessfulBuild/artifact/a/Minepacks-2.4.11-Release.jar).
