### ISSUE TITLE
Problem with auto-loot

### ISSUE THREAD

**Issue by Kamikazepazzo** [GeorgH93/Minepacks#241]
Hi,  have this problem, when i see that my inventory is full, sometimes the backpack work and loot but sometimes not work and don't recognize the stuff, how i can do?

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/312/artifact/a/Minepacks-2.4.12-Release.jar).
