### ISSUE TITLE
Autopickup not working

### ISSUE THREAD

**Issue by mape14** [GeorgH93/Minepacks#242]
Hi!

I'm using your plugin and I can't use the autopickup feature, I can't even toggling /backpack pickup, it's like the command doesn't even exist. 

I'm using 2.4.11 release version and, of course, have op permissions.

Thanks!

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/312/artifact/a/Minepacks-2.4.12-Release.jar).
