### ISSUE TITLE
<lang:> tag inside backpack inventory

### ISSUE THREAD

**Issue by botprzemek** [GeorgH93/Minepacks#245]
![image](https://user-images.githubusercontent.com/92102878/214565984-8bd364b8-75b0-4589-85b2-a6bc33126332.png)

**What I have tried**
I tried adding my locale, and switch to english. It does not seem to work, formatting is broken with Oraxen's minimessage overriding.

**Comment by GeorgH93** [comment]
Sorry, no support for paid plugins.
