### ISSUE TITLE
Boostrap error

### ISSUE THREAD

**Issue by Joker112112** [GeorgH93/Minepacks#266]
### Information
**Environment information**
*Plugin + server version info*:

```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*:  no 

*BungeeCord*: no 

**Server/crash log**
<html>
<body>

[18:47:42] [ServerMain/ERROR]: [BootstrapProviderStorage] Failed to run bootstrapper for plugins/Minepacks.jar. This plugin will not be loaded.
--
2 | java.lang.AbstractMethodError: Receiver class at.pcgamingfreaks.Minepacks.Paper.MinepacksBootstrap does not define or inherit an implementation of the resolved method 'abstract void bootstrap(io.papermc.paper.plugin.bootstrap.BootstrapContext)' of interface io.papermc.paper.plugin.bootstrap.PluginBootstrap.
3 | at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:34) ~[paper-1.19.4.jar:git-Paper-549]
4 | at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:22) ~[paper-1.19.4.jar:git-Paper-549]
5 | at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[paper-1.19.4.jar:git-Paper-549]
6 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-549]
7 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-549]
8 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:26) ~[paper-1.19.4.jar:git-Paper-549]
9 | at net.minecraft.server.Bootstrap.lambda$bootStrap$0(Bootstrap.java:75) ~[?:?]
10 | at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:321) ~[paper-1.19.4.jar:git-Paper-549]
11 | at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:73) ~[?:?]
12 | at net.minecraft.server.Main.main(Main.java:127) ~[paper-1.19.4.jar:git-Paper-549]
13 | at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[paper-1.19.4.jar:git-Paper-549]
14 | at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
15 | at java.lang.Thread.run(Unknown Source) ~[?:?]

</body>
</html>

```

**Plugin config (optional)**
<!-- Some problems are depending on the used configuration. To enable us to help you faster you can provide us with some details about your config or the full config.yml file (please use https://gist.github.com/ to upload your config.yml, make sure to remove confidential informations like database passwords!) -->
```

```

### Details
**Description**  
Minepacks wont even start when I try to run /backpack or /bp it says unknown command

**Steps to reproduce**  
<!-- Replace this with what exactly you did to cause the bug. -->

**Expected behavior**  
<!-- Replace this with what you expect to happen. -->

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
<!-- Replace this with any additional information, if necessary. -->

**Comment by GeorgH93** [comment]
Downgrade paper to 548 (they pushed breaking API changes without warning again) or update the plugin to [v2.4.20.1](https://github.com/GeorgH93/Minepacks/releases/tag/v2.4.20.1).

**Comment by mooonwaltz** [comment]
i'm sorry to ask, but will this issue be fixed soon? my server plays on aternos, and unfortunately, i cannot execute either of these solutions. no rush, of course, im simply wondering if it's something i can look forward to.

**Comment by GeorgH93** [comment]
> i'm sorry to ask, but will this issue be fixed soon? my server plays on aternos, and unfortunately, i cannot execute either of these solutions. no rush, of course, im simply wondering if it's something i can look forward to.

I guess they fetch it directly from curseforege, so you will have to wait till curseforge approves the update.
