### ISSUE TITLE
Getting this big Error reguarding API Key

### ISSUE THREAD

**Issue by RyanNuggyen** [GeorgH93/Minepacks#274]
### Help request

**Problem**

Getting a huge error line in my console regarding an API key being rejected.

https://mclo.gs/FMZKVO4

https://gist.github.com/RyanNuggyen/b5cf975d3dc42642f6886d55683ffb4e
**What I have tried**

Restarting and redownloading

**Comment by GeorgH93** [comment]
It failed to check for updates with the GitHub API, probably just a temporary rate limit or outage issue. Should be save to ignore for now.
