### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by pjindras** [GeorgH93/Minepacks#276]
### Information
Purpur 1.20.1 (always lastest)
```

2.4.21.1

```

*Online mode*: false

*BungeeCord*: no

Hello, when I set in luckperms permission for the backpack size to some group, some players from that group still unfortunately see only 1 row backpack, after using /backpack command.

**Comment by GeorgH93** [comment]
I just released [v2.4.22](https://github.com/GeorgH93/Minepacks/releases/download/v2.4.22/Minepacks-2.4.22-Release.jar), it should address this issue.
