### ISSUE TITLE
Backpack Shortcut item does not appear in the inventory

### ISSUE THREAD

**Issue by MrJuzz** [GeorgH93/Minepacks#281]
### Information
**Environment information**
*Plugin + server version info*:

[INFO] ....>.... ##### Start Minepacks version info #####

[INFO] .... Minepacks: 2.4.23-T20230923230740

[INFO] .... Server: git-Paper-249 (MC: 1.20.2)

[INFO] .... Java: 19.0.2

[INFO] .... ##### End Minepacks version info #####

```

*Online mode*: no

*BungeeCord*: no

**Server/crash log**
<!-- If you see an error message in the console/log please provide it. Please provide at least 10 lines befor and after the error! If you like to share the full log file please use https://gist.github.com/
The log can contain user related information like ip, name or uuid, so please replace them if they are not necessary. -->
```

I did not get an error message

```

**Plugin config (optional)**
<!-- Some problems are depending on the used configuration. To enable us to help you faster you can provide us with some details about your config or the full config.yml file (please use https://gist.github.com/ to upload your config.yml, make sure to remove confidential informations like database passwords!) -->
```

ItemShortcut:
  Enabled: true
  ItemName: "&eMochila"
  HeadTextureValue: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmRmY2VlODMwNmUwNDM0YTc0NzcxMGUyYmRjMjU1OGM1YTIyMmU5YjY5MzQ3NzkwOWYxMGQ2Y2MyMjBmNjc2NCJ9fX0="
 
  ImproveDeathChestCompatibility: true
  BlockAsHat: false
  OpenContainerOnRightClick: true
  PreferredSlotId: 5
  BlockItemFromMoving: false

```

### Details
**Description**  
the backpack item is not displayed, even when it is enabled by default

**Steps to reproduce**  
No need to replicate, the configuration I had is already shared and by default the shortcut item is activated. 

**Expected behavior**  
I would expect it to show me the backpack item in the inventory, in this case configured to appear by default in slot 5.   
![Captura de pantalla 2023-10-28 231632](https://github.com/GeorgH93/Minepacks/assets/45012203/c5560cc1-735f-4f1f-94fd-936cbdb0c243)


**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
<!-- Replace this with any additional information, if necessary. -->

**Comment by GeorgH93** [comment]
The item is only given to players that have the permission to use the backpack, when changing world, spawning or connecting. If the player is given the permission later, it will only appear in their inventory once they switch world, reconnect or respawn.
To make sure the player has the necessary permission they should be able to open the backpack with `/backpack open`.
