### ISSUE TITLE
Get the backpaclk with a command 

### ISSUE THREAD

**Issue by Snic0509** [GeorgH93/Minepacks#282]
**Problem**
Hey we have the problem that we want do set up a quest where we can give the player the backpack with a give command 

**What I have tried**
we have searched sore multiple commands

**Comment by GeorgH93** [comment]
[This build](https://ci.pcgamingfreaks.at/job/Minepacks/368/artifact/a/Minepacks-2.4.24-SNAPSHOT-Release.jar) adds a hidden `/backpack shortcut` and `/backpack shortcut <playername>` command to trigger the item checking logic (normally only triggered on change world, respawn and join).
You could use this with whatever script you are using for your quest to give the player the permission and then run the command to add the item to the players inventory directly.
