### ISSUE TITLE
Permissions also affect OP players

### ISSUE THREAD

**Issue by Bel-Dias** [GeorgH93/Minepacks#291]
### Feature request
  Permissions also affect OP players.

**Feature description**

  Backpack of OP players also limited by permissions.

**How the feature is useful**

  On small servers, OP players may want to have the same experience as other players.
And increase backpack functions (such as maximum size, whether it will contain items when you die, etc.) as you complete quests. Instead of already having all functions released.

  So it would be interesting if the functions were only released if the player had the permissions, regardless of whether they were OP or not.

**Comment by GeorgH93** [comment]
You should be able to do this using your permissions plugin by negating the permissions you don't want to give to op players by default.

**Comment by Bel-Dias** [comment]
It worked! Thanks!
I completely forgot about this possibility.
