### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by LittleDuck363** [GeorgH93/Minepacks#317]
### Help request

**Problem**
Minepacks crashes players games when they try to use them.

**What I have tried**
I updated versions and even attempted the basic standalone version.

**Comment by GeorgH93** [comment]
Details?
Server Version? Plugins? Client Version?

**Comment by Zoriot** [comment]
1.20.6 Paper (and Forks of Paper which is Purpur) isn’t supported right now. You need to wait for an Plugin update
