### ISSUE TITLE
Backpack kicking players out the server

### ISSUE THREAD

**Issue by L-ELi-oofer** [GeorgH93/Minepacks#318]
### Information
**Environment information**
*Plugin + server version info*:

```

2.4.29-T20240514070323
```

*Online mode*: Yes
*BungeeCord*: No

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Each time a player opens the backpack, it kicks them out the server. I am playing on a java geyser minecraft server on Aternos. Before we updated to the latest version, we couldn't even open the backpacks at all since minecraft was more updated. 

**Steps to reproduce**  
I updated the minepacks once they were able to, but once I did it just kicks whoever opens the backpack in the game. 

**Expected behavior**  
I guess I expect it to be fixed soon or find a solution. 

![image_2024-05-19_181344221](https://github.com/GeorgH93/Minepacks/assets/57502182/e484eb48-825f-4070-a14f-ace8a0d7560a)

**Comment by GeorgH93** [comment]
Paper based servers aren't yet supported on MC 1.20.5 and 1.20.6

**Comment by L-ELi-oofer** [comment]
do you know when they will be?

**Comment by yichifauzi** [comment]
now they update the stable version will you support it?

**Comment by helio-cat** [comment]
I'm having the exact same error as OP. On Paper/Spigot-Geyser-Floodgate serer. 
MC 1.20.6
Minepacks v2.4.29
May 14, 2024

> ##### Start Minepacks version info #####
> Minepacks: 2.4.29-T20240514070323
> Server: 1.20.6-2218-ec1b4fa (MC: 1.20.6>
> Java: 21.0.3
> ##### End Minepacks version info #####/

> Current Purpur Version: 1.20.6-2218-ec1b4fa (MC: 1.20.6)*
> * You are 3 version(s) behind
> Download the new version at: https://purpurmc.org/downloads
> Previous: git-Purpur-2176 (MC: 1.20.4)
