### ISSUE TITLE
Error in Minepacks

### ISSUE THREAD

**Issue by Acetaminofenuwu** [GeorgH93/Minepacks#335]
### Information
**Environment information**
*Plugin + server version info*:
Plugin Ver: 2.4.31.4 Server ver: 1.20.4

"/backpack version": I can't, the plugin is in red when I put /pl in my console.

*Online mode*: no, I used offline mode.

*BungeeCord*: no

**Server/crash log**
I get this error in the minepacks plugin and I don't know why.
Log error: https://mclo.gs/1l5TCay

**Plugin config (optional)**

Config file: https://mclo.gs/IbtFVNj

### Details
**Description**  
Plugin in red when I Put /pl in my console and error in console about the plugin.
**Steps to reproduce**  
I put the plugin on my server and I disabled the backpacks, work good but after days I saw the plugin is in red and don't work the commands etc.
**Expected behavior**  
Work plugin again.
**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
No

**Comment by Acetaminofenuwu** [comment]
Please Help me @GeorgH93

**Comment by GeorgH93** [comment]
Line 165, you are missing the " before world_nether.
`FilteredWorlds: ["em_fireworks", "world", world_nether"`

**Comment by Acetaminofenuwu** [comment]
Thank U 🌸❤️
