### ISSUE TITLE
Shulker Boxes are allowed inside backpack

### ISSUE THREAD

**Issue by BluDragyn** [GeorgH93/Minepacks#45]
### Information
**Environment information**
*Plugin + server version info*:
31.07 19:01:46 [Server] INFO ##### Start Minepacks version info #####
31.07 19:01:46 [Server] INFO Marriage Master: 2.0.8-Release
31.07 19:01:46 [Server] INFO Server: git-Paper-152 (MC: 1.14.4)
31.07 19:01:46 [Server] INFO #####  End Minepacks version info  #####
```

<!-- Replace this with the output of "/backpack version". You can run the command in your console or as op ingame. -->

```

*Online mode*: Yes
*BungeeCord*: No

**Server/crash log**
N/A
```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**
https://gist.github.com/BluDragyn/3f899486b6e108cb2762928f1074d964
```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Shulker boxes (un-dyed) are allowed inside backpack, even with config set to "false"

**Steps to reproduce**  
Place an un-dyed shulker in your backpack

**Expected behavior**  
For this to not be allowed

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
https://i.postimg.cc/J4HXy44W/2019-07-31-15-06-28.png

Edit: forgot to paste in backpack config

**Comment by GeorgH93** [comment]
Thanks for the report. Fix in this build: https://ci.pcgamingfreaks.at/job/Minepacks/114/artifact/artifacts/Minepacks-2.0.9-Release.jar
