### ISSUE TITLE
setting the backpacks columns (rows) to any thing less than 6, results in a one row bp

### ISSUE THREAD

**Issue by matarbuckle** [GeorgH93/Minepacks#46]
when i open up the config file to edit the bp size, it has an area for max size. its set to 6 by default but when i change it to 3, the bp just shrinks to 1 row (9 slots)

**Comment by GeorgH93** [comment]
What's the max permission size is that will be searched for, if you set it to 3 and your player has the permission `backpack.size.6` it will fail to find a size permission as only `backpack.size.1`, `backpack.size.2` and `backpack.size.3` will be checked. The player always has the `backpack.size.1` permission as long as he has the `backpack.use` permission. This results in the player having only 1 row.
The option is there to allow backpacks with more than 6 rows (with broken ui) or to improve performance on backpack open for servers that will never allow backpacks bigger than the set value.
