### ISSUE TITLE
More Backpacks

### ISSUE THREAD

**Issue by RealQuerter** [GeorgH93/Minepacks#47]
### Feature request

**Feature description**
 More backpacks per player, all of them might be the same size, just an option to have more than one backpack.

**How the feature is useful**
 The backpacks quickly run out of space. It would be useful to have something like PrivateVaults, where you can do /bp 1, /bp 2...

**Comment by GeorgH93** [comment]
It is currently planned to add multiple pages with the v2.1 update, details: https://github.com/GeorgH93/Minepacks/issues/5
There also is the plan to add per world backpacks, details: https://github.com/GeorgH93/Minepacks/issues/15

I think having one bigger (multi page) backpack would be more convenient to use than having multiple separated backpacks.

**Comment by RealQuerter** [comment]
True. It will be more intuitive. Thanks for telling me.
