### ISSUE TITLE
Allow multiple backpacks like playervaults allows multiple vaults.

### ISSUE THREAD

**Issue by Klawdek** [GeorgH93/Minepacks#52]
### Feature request

**Feature description**

I think it would be nice if players could have multiple backpacks. 
**How the feature is useful**

It would allow admins to give more options to players when ranking up.  It would also make a nice donor ranks option.
This is a great plugin and multiple backpacks would make it even better.🙂

**Comment by GeorgH93** [comment]
It will be implemented as multiple pages for one backpack. See this for more details: https://github.com/GeorgH93/Minepacks/issues/5
