### ISSUE TITLE
[REQUEST] Physical Backpack Items

### ISSUE THREAD

**Issue by DannyBeisner** [GeorgH93/Minepacks#56]
I thought it would be extremely neat for physical backpacks to be introduced to this plugin. Physical as in an item is a backpack. Backpacks that are customizable so can have 54 slots (large), 27 slots (medium), 9 slots (small), and 5 slots (tiny). I feel like this would be great because as is, Minepacks has a bit of a player vault feeling rather than backpack. I guess it could be cool if it forced you to have a "Backpack" in one of your hotbar slots and you could access it when you hover over it and right click.

**Comment by GeorgH93** [comment]
Please see: https://github.com/GeorgH93/Minepacks/issues/30
