### ISSUE TITLE
How to make server to not give item backpack to players anymore, only /backpack command.

### ISSUE THREAD

**Issue by baxandrei** [GeorgH93/Minepacks#63]
How to make server to not give item backpack to players anymore, only /backpack command?
My players hate backpack item (head), they want only /backpack command like /enderchest, without any head in inventory.

**Comment by GeorgH93** [comment]
Change the `ItemShortcut.Enabled` [config option](https://github.com/GeorgH93/Minepacks/blob/master/resources/config.yml#L156) to false.

**Comment by baxandrei** [comment]
Thanks man!
