### ISSUE TITLE
[Bug] Shelkers are able to get in Backpack

### ISSUE THREAD

**Issue by Azatramus** [GeorgH93/Minepacks#65]
I am able to put shelker boxes inside the backpack. All i do is hover my mouse over one of the backpack slots and press the number of my hotbar that my shelker box is in and it goes into that inventory slot and i can close it. I left and logged back in to make sure it wasn't client sided and its still in there.  PreventInBackpack: true in config so, by normal means dragging it doesnt work. It's just that instance.  This also works for the backpack itself, which is pointless it only duplicates the item itself, not the items within the backpack, just figured you'd like to know

**Comment by Azatramus** [comment]
https://imgur.com/a/q6Hiegk

**Comment by GeorgH93** [comment]
Thanks for the report, I will provide a bugfix asap.

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://ci.pcgamingfreaks.at/job/Minepacks/159/artifact/a/Minepacks-2.1.7-Release.jar

**Comment by Azatramus** [comment]
Good job, fixed that pretty fast lmao. Im new to java lol trying to get used to it very good! Case closed
