### ISSUE TITLE
When shortcut item put in a chest, it increase.

### ISSUE THREAD

**Issue by ethernetcat** [GeorgH93/Minepacks#67]
### Information
**Environment information**
*Plugin + server version info*:

```
Minepacks 2.1.8-Relese
git-Paper-100(MC:1.15.2)
```
*Online mode*: no

*BungeeCord*: yes

**Plugin config**
https://gist.github.com/ethernetcat/150293cb0cd8de4628e67c6a2f55ba0b

### Details
**Description**  
I don't know if this is a bug, but I can put shortcut items in your chest.

**Steps to reproduce**  
1. Store shortcut items in chests.
2. logout & login.
3. Shortcut items increase.

**Expected behavior**  
When a shortcut item moves to the chest, the shortcut item returns to the inventory.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
If this is not a bug, it is a suggestion.
This allows players to mass produce shortcut items. This has no significant effect, but is not desirable.

**Comment by GeorgH93** [comment]
How are you moving it into your chest? That should not be possible.

**Comment by ethernetcat** [comment]
I checked this issue again.
Then the plugin worked as expected.
Maybe the issue was triggered by another plugin.

I'm so sorry.
Close this issue.
