### ISSUE TITLE
Minepacks/death chest unique interaction

### ISSUE THREAD

**Issue by SleuthCyber** [GeorgH93/Minepacks#71]
### Information
**Environment information**
*Plugin + server version info*: Minepacks 2.3.1-Release 
Server: git-Bukkit-8160e29 MC 1.15.2

```



```

*Online mode*: yes
*BungeeCord*: no

**Server/crash log**

```



```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Whenever a user dies and collects their previous inventory with death chests, they get multiple backpacks. Only way to reduce the number is with creative mode. There are no separate inventories, just a minor annoyance.

**Steps to reproduce**  
Die, collect inventory, more backpacks

**Expected behavior**  
Prevention of collecting more than one backpack/auto deleting spares.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
I have added a[ config option](https://github.com/GeorgH93/Minepacks/blob/1a619037fb859a48ea1c1771ff7f9b8fc8ccdeb1/Minepacks/resources/config.yml#L176) with [this build](https://ci.pcgamingfreaks.at/job/Minepacks/173/artifact/a/Minepacks-2.3.2-Release.jar), that allows to improve compatibility with some death chest plugins. If it does not fix the problem for your death chest plugin there is nothing I can do.
