### ISSUE TITLE
[Feature Request] Dedicated backpack/chest interaction

### ISSUE THREAD

**Issue by s-kk** [GeorgH93/Minepacks#74]
### Feature request

**Feature description**

Currently, when I click on a chest with Minepack shortcut on my hand, Minepack would open. The request is that do not open Minepack when clicking normal chests, open chests instead.
**How the feature is useful**

This would decrease confusion between chests and backpacks.

**Comment by s-kk** [comment]
A little update: I figured that it's better to have dedicated interaction between Minepacks and interactive blocks/items. 
Some examples: 
Minepacks and door;
Minepacks and furnace;
Minepacks and crafting table;
Things like that...

Thanks again dev!

**Comment by GeorgH93** [comment]
[This build](https://ci.pcgamingfreaks.at/job/Minepacks/181/artifact/a/Minepacks-2.3.4-RC2-Release.jar) should add an config option to allow interactions with blocks that have an inventory (chest, shulkerbox, furnace, ...).
I will add an option for other interactions later.

**Comment by s-kk** [comment]
Thanks dev! This plugin is getting better and better!
