### ISSUE TITLE
God BackPack

### ISSUE THREAD

**Issue by CrazyMoth00** [GeorgH93/Minepacks#75]
DropOnDeath is set to true, and the player has no permission for backpack.keepOnDeath, yet the contents of the backpack doesn't gets dropped.

Oh my.. There is more to cover.
1st Situation: When a player dies with items in their backpack, on death 2 times more items spawn.

2nd Situation: The player dies and the contents of the backpack doesn't gets dropped.

3rd Situation: The items from the backpack are gets dropped, but the player's full inventory remains.

**Comment by GeorgH93** [comment]
Could you please provide me with your Minepacks config file (remove database credentials).
What is the output of `/backpack version` (it shows more than the Minepacks version, please include the full output).
Which other plugins are you using? Please also provide the config for these plugins that perform inventory actions on death (like death chest plugins).
