### ISSUE TITLE
players not getting a backpack

### ISSUE THREAD

**Issue by Talfereg** [GeorgH93/Minepacks#79]
.# If enabled the players will be given an item they can interact with to open the backpack.
  .# The item may not be removed from their inventory as long as this option is enabled.
  Enabled: true

My players are not getting a backpack unless they are OP.

Do I need to have backpack.use permission set?

Minecraft version: 1.15.2

**Comment by Talfereg** [comment]
I figured it out. Setting the backpack.use permission worked!

**Comment by GeorgH93** [comment]
Yes, they need the `backpack.use` permission. Without the permission they would not be able to use the backpack and therefor there is no reason to give them the item.

**Comment by Talfereg** [comment]
Thanks!
