### ISSUE TITLE
duplicate backpack on the bar

### ISSUE THREAD

**Issue by Oscarinelx** [GeorgH93/Minepacks#80]
### image: https://fotos.subefotos.com/49ccc5dc8d04c9bfb6493d3cff4234b5o.png

**Comment by GeorgH93** [comment]
Please turn on the [ImproveDeathChestCompatibility](https://github.com/GeorgH93/Minepacks/blob/f86e30bd6af31a8dcb2ef2b78552aef5f92288a6/Minepacks/resources/config.yml#L176) config option.

**Comment by Oscarinelx** [comment]
Sorry, I had it disabled, it works fine.
thanks for answering
