### ISSUE TITLE
Backpack Items are removed upon plugin reload.

### ISSUE THREAD

**Issue by ooULuckyoo** [GeorgH93/Minepacks#85]
When I do the command /bp reload all the data from ALL player's backpacks are reset. I am not understanding why this happens.

**Comment by GeorgH93** [comment]
Could you please provide me with your log, config and the output of `/backpack version`.

**Comment by ooULuckyoo** [comment]
Minepacks: 2.3.5-Release
Server: git-Paper-185 (MC: 1.15.2)
Java: 1.8.0_251

It appears the issue has resolved itself for now, I will contact you again if I have another issue. Perhaps an entire server restart was required after editing the configuration file.
