### ISSUE TITLE
backpack is not working

### ISSUE THREAD

**Issue by WarrenSorosHarper** [GeorgH93/Minepacks#93]
i tried everything to have the backpack for everyone on  the server for people who are not op and its not letting them use it and i tried everything and it just will not let it work on anyone expect the op. can you either fix the glitch or tell me the other way to get it too work.. please and thanks

**Comment by GeorgH93** [comment]
Players need at least the `backpack.use` permission. I would recommend to give them the `backpack.user` and a size permission e.g. `backpack.size.6` (for 6 rows).
If you do not have a permission plugin please check out this: https://github.com/GeorgH93/Minepacks/wiki/FAQ
