### ISSUE TITLE
Plugin crashing server on newest paper

### ISSUE THREAD

**Issue by MrTalon63** [GeorgH93/Minepacks#94]
I'm using the latest version of plugin and paper and from nowhere plugin starts to crash server every 30 seconds.

logs: https://pastebin.com/yAp6ve0J

**Comment by GeorgH93** [comment]
The `[10:49:52 WARN]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariPool] Minepacks-Connection-Pool - Thread starvation or clock leap detected (housekeeper delta=47s988ms81µs202ns)` message is not the cause of your problem but one of the consequences. Your server was lagging, which caused the scheduled task for the  database connection pool housekeeping to be delayed.
If you resolve your lagg problem this will also be resolved.

**Comment by MrTalon63** [comment]
Ok, I'm sorry for inconvenience.
