### ISSUE TITLE
I need help with perms

### ISSUE THREAD

**Issue by m2rsh7ll** [GeorgH93/Minepacks#96]
### Help request

**Problem**

I'm new to setting up plugins? How do I make it so that all players can use the /backpack command? Currently only I can and all other players get "you do not have the permission to do that" message.

**What I have tried**

I looked through config.yml but I'm stumped. Thank you.

**Comment by GeorgH93** [comment]
Players need at least the `backpack.use` permission in order to be able to use the plugin. You can add it with your permission plugin. If you don't have a permission plugin, you can use the permissions.yml file, like described [here](https://github.com/GeorgH93/Minepacks/wiki/FAQ).

**Comment by m2rsh7ll** [comment]
Thanks!

**Comment by ishKiia** [comment]
I really appreciate this answer.  I do have one more question, can you give permissions in that permissions.yml individually? 
For example it would be nice to have them earn a row at a time by doing things in events.   So I guess I'm asking if there is a way I could change that permissions yml to reflect each user's permissions

**Comment by GeorgH93** [comment]
> 
> 
> I really appreciate this answer. I do have one more question, can you give permissions in that permissions.yml individually?
> For example it would be nice to have them earn a row at a time by doing things in events. So I guess I'm asking if there is a way I could change that permissions yml to reflect each user's permissions

No, the permissions.yml trick only works if you want to set permissions for all players, none-op players or op players.
For anything more you will need a permission plugin like [LuckPerms](https://www.spigotmc.org/resources/luckperms.28140/). Most permission plugins also allow you to define some kind of promotion ladders ([tracks in LuckPerms](https://github.com/lucko/LuckPerms/wiki/Tracks)) that would allow you to easily implement players gaining rows for doing events.

**Comment by ishKiia** [comment]
Thank you very much!!
