### ISSUE TITLE
Minepacks plugin installed but can't do commands (minehut 1.16)

### ISSUE THREAD

**Issue by squeeto** [GeorgH93/Minepacks#97]
### Help request

**Problem**

When minehut updated to 1.16 the minepack commands stopped working.
**What I have tried**

 So far I tried uninstalling and reinstalling the plugin and I also reset the config file

**Comment by GeorgH93** [comment]
They are probably using an old version of Minepacks. Please contact the Minehut support about this.

**Comment by squeeto** [comment]
Ok thank you!
