### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by MrTalon63** [GeorgH93/Minepacks#98]
**Environment information**
*Plugin + server version info*:

>....=>.... [19:12:20 INFO]: ##### Start Minepacks version info #####
>.... [19:12:20 INFO]: Minepacks: 2.3.10-Release
>.... [19:12:20 INFO]: Server: git-Paper-368 (MC: 1.15.2)
>.... [19:12:20 INFO]: Java: 11.0.6
>.... [19:12:20 INFO]: ##### End Minepacks version info #####

*Online mode*: no

*BungeeCord*: yes
**Server/crash log**
https://pastebin.com/YkyuUNWn

**Plugin config (optional)**

https://gist.github.com/MrTalon63/9261f351f48b688b638bb200cc3adb39

### Details
**Description**  
Plugin can't create table

**Steps to reproduce**  
Put in MySQL as storage
reload
put items
reload
no items in backpack

**Expected behavior**  
keep items inside

**Comment by MrTalon63** [comment]
Also, when I type the password in it add space
    Password: "	PASSWORD"
like that

**Comment by GeorgH93** [comment]
Could you please provide me with the log from when you reloaded the plugin? It looks like there was a problem creating the tables there.


> 
> 
> Also, when I type the password in it add space
> Password: " PASSWORD"
> like that

Do you have any special chars (especially `'`, `"` and `#`) in your password?

**Comment by MrTalon63** [comment]
As it's randomly generated I have 2 dots

**Comment by MrTalon63** [comment]
Okay, so I regenerated password couple of times and I got lucky and have password without any special characters. When I will be home I will check if it works now.

**Comment by MrTalon63** [comment]
Same error with password _iBtgdFCUWxK7YjeXTtEWen7b_ (it's changed now)

https://gist.github.com/MrTalon63/cdf17f82f731e3b7a7a2f1125e436b14

**Comment by MrTalon63** [comment]
I tried using MySQL from my web hosting and I have whole another error about timezones

https://gist.github.com/MrTalon63/26f7cfd30d50e5bc0c2fcf6d2f4bda24

**Comment by GeorgH93** [comment]
> 
> 
> I tried using MySQL from my web hosting and I have whole another error about timezones
> 
> https://gist.github.com/MrTalon63/26f7cfd30d50e5bc0c2fcf6d2f4bda24

You should be able to prevent the timezone error by setting the properties config option to this:
`Properties: [ "useSSL=false", "serverTimezone=UTC" ]`



> 
> 
> Same error with password _iBtgdFCUWxK7YjeXTtEWen7b_ (it's changed now)
> 
> https://gist.github.com/MrTalon63/cdf17f82f731e3b7a7a2f1125e436b14

Just to make sure, remote connections to your database are allowed for your user?

**Comment by MrTalon63** [comment]
So with that timezone flag, everything works just fine. And yes I have % character in my hosts MySQL manager
